UpVent/UpVent/urls.py
# Import settings if not imported
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

# Import robots.txt
from core.views import robots_txt

# Import sitemaps
from core.sitemaps import StaticViewSitemap, BlogSitemap

handler404 = 'core.views.page_not_found'

sitemaps = {
    'static': StaticViewSitemap,
    'posts': BlogSitemap,
}

urlpatterns = [
    # Special URL's (Mostly admin or managed things)
    path('wp-admin/doc/', include('django.contrib.admindocs.urls')),
    path('captcha/', include('captcha.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('wp-admin/', admin.site.urls),
    path('robots.txt', robots_txt),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    # Main Site URLs
    path('', include('core.urls'), name='index'),
    path('blog/', include('blog.urls', namespace="blog"), name='blog'),
    path('contact/', include('contact.urls', namespace="contact"),
         name='contact'),
    path('marketcloud/', include('marketcloud.urls', namespace="marketcloud"),
         name='marketcloud'),
]

admin.site.site_header = "UpVent Admin"
admin.site.index_title = "Admin"
admin.site.site_title = "UpVent"

# Special URL's for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UpVent/blog/urls.py
from django.urls import path
from .views import Blog, BlogEntry, BlogSearch

app_name = 'blog'

urlpatterns = [
    path('', Blog, name='home'),
    path('entry/<slug>/', BlogEntry, name='post'),
    path('search/', BlogSearch, name='blog-search'),
]

UpVent/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

class Post(models.Model):
    """
    Stores a single blog post. It is only related to :model:`auth.User` to set
    the blog author.
    """

    # Current blog post status
    STATUS = (
        (0, "Draft"),
        (1, "Published")
    )

    # Blog Title
    title = models.CharField(
        verbose_name="Título",
        max_length=200,
        unique=True,
        help_text="Título del post",
        blank=False
    )

    # SEO Description
    description = models.CharField(
        verbose_name="Descripción",
        max_length=200,
        default="",
        help_text="Descripción del post. Usada para mostrarse en motores de\
        búsqueda y en redes sociales como un texto corto.",
        blank=False
    )

    # Blog portrait
    image = models.ImageField(
        verbose_name="Imágen Destacada",
        upload_to="posts",
        help_text="Portada del post. Se recomiendan imágenes rectangulares.",
        blank=False
    )

    # Blog category
    category = models.CharField(
        verbose_name="Categoría",
        max_length=20,
        default='None',
        help_text="Categoría a la que pertenece el post.",
        blank=False
    )

    # Blog slug (autogenerated)
    slug = models.SlugField(
        verbose_name="Slug",
        max_length=200,
        unique=True,
        help_text="Campo autogenerado. Modifique de acuerdo a sus necesidades",
        blank=False
    )

    # Blog author (get from current user)
    author = models.ForeignKey(
        User,
        verbose_name="Autor",
        on_delete= models.CASCADE,related_name='blog_posts',
        help_text="Seleccione el autor del post",
        blank=False
    )

    # Blog last update date
    updated_on = models.DateTimeField(
        verbose_name="Actualizado el: ",
        auto_now= True
    )

    # Blog content (Handled by CKEditor)
    content = RichTextUploadingField(
        verbose_name="Contenido",
        help_text="Contenido detallado del post"
    )

    # Blog creation date
    created_on = models.DateTimeField(
        verbose_name="Creado el: ",
        auto_now_add=True
    )

    # Blog publishing status
    status = models.IntegerField(
        choices=STATUS,
        default=0,
        help_text="Estatus actual del post"
    )

# ----- Blog side panel attributes -----

    # Blog side title
    side_title = models.CharField(
        verbose_name="Título Lateral",
        max_length=200,
        default="Otros Recursos",
        help_text="Título de la imágen que aparecerá en la parte derecha de\
        cada post",
        blank=False
    )

    # Blog Side image
    side_img = models.ImageField(
        verbose_name="Imágen Lateral",
        upload_to="posts",
        help_text="Imágen que aparecera en la parte derecha de cada post.\
        puede usarse para publicidad u otros fines.",
        blank=False
    )

    # Blog side text title
    side_text_title = models.CharField(
        verbose_name="Título Lateral",
        max_length=200,
        default="Título del recurso",
        help_text="Título del texto inferior que aparecerá en la parte derecha\
        de cada post",
        blank=False
    )

    # Blog side text
    site_text = models.TextField(
        verbose_name="Texto Lateral",
        default="Ver más",
        help_text="Texto mostrado en la parte derecha de cada post, debajo de\
        la imágen lateral.",
        blank=False
    )

    # Blog side button
    side_button = models.CharField(
        verbose_name="Texto del botón lateral",
        max_length=50,
        default="Leer más...",
        help_text="Texto que mostrará el botón mostrado en la parte derecha\
        de cada post.",
        blank=False
    )

    # Blog side button url
    side_button_url = models.URLField(
        verbose_name="URL del botón lateral",
        default="https://upvent.codes",
        help_text="Sitio al que dirigirá el botón lateral mostrado en la parte\
        derecha de cada post",
        blank=False
    )

    side_video_title = models.CharField(
        verbose_name="Texto del vídeo lateral",
        max_length=100,
        default="Conocer más",
        help_text="Texto que se mostrará como título del vídeo lateral",
        blank=False
    )

    # Blog side video
    side_video = models.URLField(
        verbose_name="Video Lateral",
        default="https://upvent.codes",
        help_text="URL hacia un vídeo que será mostrado en la parte derecha de\
        cada post.",
        blank=False
    )

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def get_absolute_url(self):
        return reverse("blog:post", args={
            self.slug
        })

    def __str__(self):
        return self.title

UpVent/blog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import JsonResponse

from .models import Post

def Blog(request):

    """
    Display all :model:`blog.Post` saved in the database ordered by ID and
    only those who are marked with status 1 (Published).

    Any blog post marked with status 0 (Draft) will be hidden.

    **Context**

    ``Post``
        An instance of :model:`blog.Post`.

    **Template**
        :template:`blog/blog.html`

    """

    articles = Post.objects.filter(status=1).order_by("created_on")
    paginator = Paginator(articles, 6)

    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)

    return render(request, 'blog/blog.html', {'posts':posts})

def BlogEntry(request, slug):

    """
    Display a single detailed view of a single :model:`blog.Post` when clicked
    in the :template:`blog/blog.html` view.

    **Context**

    ``Post``
        - An instance of :model:`blog.Post`
        - The blog post slug for friendly url handling

    **Template**
        :template:`blog/article.html`
    """

    post = Post.objects.get(slug=slug)

    context = {
        'post': post,
    }

    return render(request, 'blog/article.html', context)

def BlogSearch(request):
    results = {'data': []}
    posts = Post.objects.filter(title__icontains=request.POST.get('query', default="a"))[:5]
    for post in posts:
        results['data'].append({
            'image': post.image.url,
            'title': post.title,
            'description': post.description[:15],
            'url': post.get_absolute_url(),
        })
    return JsonResponse(results)

UpVent/blog/templates/blog/article.html
{% extends 'core/base.html' %}
{% load static %}
{% load humanize %}

{% block metatags %}
    <!-- Primary Meta Tags -->
    <title>UpVent - {{post.title}}.</title>
    <meta name="title" content="{{post.title}}">
    <meta name="description" content="{{post.description}}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="twitter:site" content="@UpVentMX">
    <meta property="twitter:creator" content="@UpVentMX">
    <meta property="og:title" content="{{post.title}}">
    <meta property="og:description" content="{{post.description}}">
    <meta property="og:image" content="https://upvent.codes{{post.image.url}}">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:url" content="@UpVentMX">
    <meta name="twitter:title" content="{{post.title}}">
    <meta name="twitter:description" content="{{post.description}}">
    <meta name="twitter:image" content="https://upvent.codes/{{post.image.url}}">
{% endblock %}

{% block body %}
    <div id="intro" class="p-5 text-center bg-light">
        <h1 class="mb-0 h4">{{post.title}}</h1>
    </div>
    <main class="mt-4 mb-5">
        <div class="container">
            <div class="row">
                <div class="col-md-8 mb-4">
                    <section class="border-bottom mb-4">
                        <img src="{{post.image.url}}" class="img-fluid shadow-sm rounded mb-4" alt="Portada del post" loading="lazy"/>

                        <div class="row align-items-center mb-4">
                            <div class="col-lg-6 text-center text-lg-start mb-3 m-lg-0">
                                <img src="{% static 'core/img/upvent-logo.png' %}" class="rounded shadow me-2"
                                     width="15%" alt="Imágen del autor" loading="lazy" />
                                <span>Fecha de publicación: <u class="text-muted">{{post.created_on | naturaltime}}</u> por</span>
                                <a href="https://upvent.codes" class="badge rounded-pill bg-primary text-white text-decoration-none">UpVent</a>
                                <hr />
                                <span>Última actualización: <u class="text-muted">{{post.updated_on | naturaltime}}</u></span>
                            </div>

                            <div class="col-lg-6 text-center text-lg-end">

                                <span class="text-muted">Compartir: </span>

                                <a href="https://facebook.com/UpVentMX" class="btn btn-sm btn-primary rounded-circle btn-facebook ml-2">
                                    <i class="bi bi-facebook"></i>
                                </a>
                                <a href="https://twitter.com/UpVentMX" class="btn btn-sm btn-primary rounded-circle btn-twitter ml-2">
                                    <i class="bi bi-twitter"></i>
                                </a>
                                <a href="https://github.com/UpVent" class="btn btn-sm btn-primary rounded-circle btn-github ml-2">
                                    <i class="bi bi-github"></i>
                                </a>
                                <a href="#comentarios" class="btn btn-sm btn-primary rounded-circle ml-2">
                                    <i class="bi bi-chat-fill"></i>
                                </a>
                            </div>
                        </div>
                    </section>
                    <article>
                        <p>{{post.content|safe}}</p>
                    </article>
                    <hr />
                    <section>
                        <div id="comentarios" class="container">
                            <div id="s9comments"></div>
                        </div>
                    </section>
                </div>

                <div class="col-md-4 mb-4">
                    <section class="sticky-top" style="top: 80px;">
                        <section class="text-center border-bottom pb-4 mb-4">
                            <h1>{{ post.side_title }}</h1>
                            <div class="container mb-4">
                                <img alt="Imágen patrocinada" src="{{ post.side_img.url }}" class="img-fluid" loading="lazy" />
                                <a href="{{ post.side_button_url }}" target="_blank" rel="noopener noreferrer">
                                </a>
                            </div>
                            <h5>{{ post.side_text_title }}</h5>

                            <p>{{ post.site_text }}</p>
                            <a role="button" class="btn btn-primary" href="{{ post.side_button_url }}" target="_blank" rel="noopener noreferrer">{{ post.side_button }}</a>
                        </section>
                        <section class="text-center">
                            <h5 class="mb-4">{{ post.side_video_title }}</h5>

                            <div class="embed-responsive embed-responsive-16by9 shadow-4-strong">
                                <iframe class="embed-responsive-item rounded" sandbox="allow-same-origin allow-scripts allow-popups" src="{{ post.side_video }}" allowfullscreen></iframe>
                            </div>
                        </section>
                    </section>
                </div>
            </div>
        </div>
    </main>
    {% block js %}
        <script async defer src="https://social9.com/comments/js/s9comments.js"></script>
    {% endblock %}
{% endblock %}

UpVent/blog/templates/blog/blog.html
{% extends 'core/base.html' %}
{% load static %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block metatags %}
    <!-- Primary Meta Tags -->
    <title>UpVent - El Blog Oficial de UpVent Technologies.</title>
    <meta name="title" content="UpVent - El Blog Oficial de UpVent Technologies.">
    <meta name="description" content="El blog oficial de UpVent. Aquí podras encontrar tutoriales y artículos de todo tipo para mantenerte siempre informado.">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://upvent.codes/blog">
    <meta property="og:title" content="UpVent - El Blog Oficial de UpVent Technologies.">
    <meta property="og:description" content="El blog oficial de UpVent. Aquí podras encontrar tutoriales y artículos de todo tipo para mantenerte siempre informado.">
    <meta property="og:image" content="https://upvent.codes/static/core/img/blog.png">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@UpVentMX">
    <meta name="twitter:creator" content="@UpVentMX">
    <meta name="twitter:title" content="UpVent - El Blog Oficial de UpVent Technologies.">
    <meta name="twitter:description" content="El blog oficial de UpVent. Aquí podras encontrar tutoriales y artículos de todo tipo para mantenerte siempre informado.">
    <meta name="twitter:image" content="https://upvent.codes/static/core/img/blog.png">
{% endblock %}


{% block body %}
    <div id="intro" class="p-5 text-center bg-light">
        <h1 class="mb-3">Blog</h1>
        <p class="mb-3 text-wrap lead">Bienvenido al blog de UpVent. Has llegado
            a la página principal para ver artículos sobre tecnología,
            tutoriales de programación, servidores, sistemas operativos tipo unix
            y todo tipo de contenido relacionado con el ecosistema de software libre. <i class="bi bi-heart"></i>
        </p>
        <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">Apoyar <i class="bi bi-bookmark-heart"></i></button>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal2">Compartir <i class="bi bi-share-fill"></i></button>
        </div>

        <div class="raw my-4">
            <div class="col-12 justify-content-center">
                <form id="search-form" action="{% url 'blog:blog-search' %}">
                    {% csrf_token %}
                    <div class="input-group" id="search-group">
                        <i class="bi bi-search input-group-text"></i>
                        <input type="text" class="form-control" id="search-input" placeholder="Busca por titulo">
                    </div>
                </form>
                <div id="search-results">
                </div>
            </div>
        </div>

        <!-- "Apoyar" Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Apoyar a UpVent</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <p>
                            Puedes apoyar a UpVent de las siguientes formas:
                            <ul class="list-group">
                                <li class="list-group-item"><a class="text-decoration-none" href="https://liberapay.com/VentGrey"><i class="bi bi-cash"></i> Liberapay</a></li>
                                <li class="list-group-item"><a class="text-decoration-none" href="https://vendor.cryptopayment.link/p/RZH91U2K"><i class="bi bi-credit-card"></i> Donar crypto</a></li>
                                <li class="list-group-item"><a class="text-decoration-none" href="https://github.com/UpVent/upvent.codes"><i class="bi bi-github"></i> Dar una estrella a esta página en GitHub</a></li>
                                <li class="list-group-item"><a class="text-decoration-none" href="https://web.facebook.com/UpVentMX/reviews/?ref=page_internal"><i class="bi bi-facebook"></i> Calificarnos en Facebook</a></li>
                                <li class="list-group-item"><a class="text-decoration-none" href="{% url 'licenses' %}"><i class="bi bi-star"></i> Donar a cualquier proyecto de software libre listado en nuestro salón de la fama</a></li>
                            </ul>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <!-- "Compartir" Modal -->
        <div class="modal fade" id="modal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Compartir en Redes Sociales</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a href="https://www.facebook.com/sharer/sharer.php?u=https://upvent.codes/blog" class="btn btn-primary">Facebook <i class="bi bi-facebook"></i></a>
                            <a href="https://twitter.com/intent/tweet?url=https://upvent.codes/blog&text=%C2%A1Hoy%20aprend%C3%AD%20algo%20nuevo%20en%20el%20blog%20de%20#UpVent!%20%C2%BFQuieres%20aprender%20algo%20tu%20tambi%C3%A9n?%20%20%F0%9F%91%A9%E2%80%8D%F0%9F%92%BB%F0%9F%92%BB" class="btn btn-info text-white">Twitter <i class="bi bi-twitter"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <main class="my-5">
        <div class="container">
            <section class="text-center">
                <h4 class="mb-5 fw-bold">Últimos Artículos</h4>

                <div class="row">
                    {% for post in posts %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card shadow-sm border-0">
                                <img alt="Portada de blog" src="{{ post.image.url }}" class="card-img-top" loading="lazy"/>
                                <div class="card-body">
                                    <p class="h5 card-title fw-bold">{{ post.title }}</p>
                                    <span class="badge rounded-pill bg-primary">Categoría: {{post.category}}</span>
                                    <hr />
                                    <p class="card-text text-muted fw-light pt-2 pb-3">
                                        {{post.description|truncatewords:30}}
                                    </p>
                                    <a href="{% url 'blog:post' post.slug %}" class="btn btn-primary stretched-link mt-2">Leer más... <i class="bi bi-book"></i></a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </section>
            <!-- Pagination -->
            <nav class="my-4" aria-label="...">
                <ul class="pagination justify-content-center">

                    {% if posts.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">Primero</a>
                        </li>

                        <li class="page-item">
                            <a class="page-link" href="?page={{ posts.previous_page_number }}" tabindex="-1" aria-disabled="true">{{ posts.previous_page_number  }}</a>
                        </li>
                    {% endif %}

                    <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ posts.number }}</a></li>

                    {% if posts.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{posts.next_page_number}}">{{posts.next_page_number}}</a>
                    </li>

                    <li class="page-item"><a class="page-link" href="?page={{posts.paginator.num_pages}}">Último</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </main>
{% endblock %}

{% block js %}
    <script async defer type="text/javascript" src="{% static 'blog/js/blog.js' %}"></script>
{% endblock %}