UpVent/UpVent/urls.py
# Import settings if not imported
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

# Import robots.txt
from core.views import robots_txt

# Import sitemaps
from core.sitemaps import StaticViewSitemap, BlogSitemap

handler404 = 'core.views.page_not_found'

sitemaps = {
    'static': StaticViewSitemap,
    'posts': BlogSitemap,
}

urlpatterns = [
    # Special URL's (Mostly admin or managed things)
    path('wp-admin/doc/', include('django.contrib.admindocs.urls')),
    path('captcha/', include('captcha.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('wp-admin/', admin.site.urls),
    path('robots.txt', robots_txt),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    # Main Site URLs
    path('', include('core.urls'), name='index'),
    path('blog/', include('blog.urls', namespace="blog"), name='blog'),
    path('contact/', include('contact.urls', namespace="contact"),
         name='contact'),
    path('marketcloud/', include('marketcloud.urls', namespace="marketcloud"),
         name='marketcloud'),
]

admin.site.site_header = "UpVent Admin"
admin.site.index_title = "Admin"
admin.site.site_title = "UpVent"

# Special URL's for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UpVent/blog/urls.py
from django.urls import path
from .views import Blog, BlogEntry, BlogSearch

app_name = 'blog'

urlpatterns = [
    path('', Blog, name='home'),
    path('entry/<slug>/', BlogEntry, name='post'),
    path('search/', BlogSearch, name='blog-search'),
]

UpVent/core/urls.py
from django.urls import path
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('licenses/', views.licenses, name='licenses'),
    path('team/', views.team, name='team'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('terms-of-service/', views.terms_service, name='terms-of-service'),
]


# Media Root
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UpVent/core/models.py
from django.db import models
from django.core.exceptions import ValidationError
from ckeditor_uploader.fields import RichTextUploadingField

# (index) Testimonial Model
class Testimonial(models.Model):

    """
    Stores a single instance of a testimonial made by any UpVent client.
    """

    image = models.ImageField(
        verbose_name="Foto del cliente",
        upload_to="testimonials",
        help_text="Se recomiendan imágenes cuadradas",
        blank=False
    )

    name = models.CharField(
        verbose_name="Nombre Completo",
        max_length=100,
        unique=True,
        help_text="Ingrese el nombre de la persona dando su testimonio.",
        default="",
        blank=False
    )

    testimonial = RichTextUploadingField(
        verbose_name="Testimonio",
        help_text="Testimonio de la persona."
    )

    workplace = models.CharField(
        verbose_name="Lugar de Trabajo",
        max_length=80,
        help_text="Ingrese el puesto que desempeña la persona que da el\
        testimonio.",
        blank=False
    )

    site = models.URLField(
        verbose_name="Sitio web",
        max_length=200,
        help_text="El sitio web donde se encuentra alojado el proyecto.",
        blank=False
    )

    class Meta:
        verbose_name = "Testimonio"
        verbose_name_plural = "Testimonios"

    def __str__(self):
        return self.name

# (about-us) Project model
class Project(models.Model):

    """
    Stores a single instance of a project used in the portfolio section
    in this site.
    """

    title = models.CharField(
        verbose_name="Título",
        max_length=200,
        unique=True,
        help_text="Ingrese el nombre del proyecto.",
        blank=False
    )

    image = models.ImageField(
        verbose_name="Imágen Destacada",
        upload_to="portfolio",
        help_text="Se recomiendan imágenes de dimensiones rectangulares.",
        blank=False
    )

    site = models.URLField(
        verbose_name="Sitio web",
        max_length=200,
        help_text="El sitio web donde se encuentra alojado el proyecto.",
        blank=False
    )

    description = RichTextUploadingField(
        verbose_name="Descripción",
        help_text="Descripción del proyecto. Procure ser breve."
    )

    created_on = models.DateTimeField(
        verbose_name="Fecha de Creación",
        auto_now_add=True
    )

    updated_on = models.DateTimeField(
        verbose_name="Fecha de Actualización",
        auto_now_add=True
    )

    class Meta:
        ordering = ['created_on']
        verbose_name = "Proyecto"
        verbose_name_plural = "Proyectos"

    def __str__(self):
        return self.title

# (services) Free Software Services Model
class FSProject(models.Model):

    """
    Stores a single Free Software Project shown in the "services" page of this
    site.
    """

    title = models.CharField(
        verbose_name="Título",
        max_length=100,
        help_text="Ingrese el nombre del proyecto.",
        default="",
        blank=False
    )

    image = models.ImageField(
        verbose_name="Imágen Destacada",
        upload_to="floss",
        help_text="Se recomiendan imágenes de dimensiones rectangulares.",
        blank=False
    )

    description = RichTextUploadingField(
        verbose_name="Descripción",
        help_text="Descripción del proyecto."
    )


    github_addr = models.URLField(
        verbose_name="Dirección de Git",
        max_length=200,
        help_text="URL completa del repositorio donde se encuentra el proyecto",
        default="https://github.com/",
        blank=False
    )

    support_addr = models.URLField(
        verbose_name="Dirección de apoyo",
        max_length=200,
        help_text="URL completa donde los visitantes podrán apoyar al proyecto",
        default="https://github.com/",
        blank=False
    )

    plicense = models.CharField(
        verbose_name="Licencia",
        max_length=25,
        help_text="Ingrese la licencia del proyecto",
        default="",
        blank=False
    )

    license_link = models.URLField(
        verbose_name="URL de licencia",
        max_length=200,
        help_text="URL completa para ver la licencia del proyecto",
        default="https://gnu.org/",
        blank=False
    )

    created_on = models.DateTimeField(
        verbose_name="Fecha de Creación",
        auto_now_add=True
    )

    updated_on = models.DateTimeField(
        verbose_name="Fecha de Actualización",
        auto_now_add=True
    )

    class Meta:
        verbose_name = "Proyecto de código abierto"
        verbose_name_plural = "Proyectos de código abierto"

    def __str__(self):
        return self.title

# (licenses) License Model
class License(models.Model):

    """
    Stores a single License model shown in the "licenses" page of this
    site.
    """

    name = models.CharField(
        verbose_name="Nombre",
        max_length=60,
        help_text="Ingrese el nombre de la licencia a mostrar",
        default="Gnu General Public License v2",
        blank=False
    )

    verbatim = RichTextUploadingField(
        verbose_name="Texto corto de la licencia",
        help_text="Escriba aquí el texto corto o resumen de la licencia",
        default=""
    )

    license_link = models.URLField(
        verbose_name="URL de licencia",
        max_length=200,
        help_text="URL completa para ver la licencia del proyecto",
        default="https://gnu.org/",
        blank=False
    )

    class Meta:
        verbose_name = "Licencia"
        verbose_name_plural = "Licencias"

    def __str__(self):
        return self.name

# (licenses) HOF Model
class HOF(models.Model):

    """
    Stores a single Hall Of Fame Project shown in the "licenses" page of this
    site.
    """

    name = models.CharField(
        verbose_name="Nombre",
        max_length=60,
        help_text="Ingrese el nombre del proyecto a mostrar en\
        el salón de la fama",
        default="Gnu Compiler Colection",
        blank=False
    )

    icon = models.ImageField(
        verbose_name="Icono del Proyecto",
        upload_to="licenses",
        help_text="Se recomiendan imágenes de dimensiones rectangulares.",
        blank=False
    )

    class Meta:
        verbose_name = "Proyecto del salón de la fama"
        verbose_name_plural = "Proyectos del salón de la Fama"

    def __str__(self):
        return self.name

# (team) Team member Model
class TeamMember(models.Model):
    """
    Stores a single team member to show on the 'team/' url in this page.

    The is_collab field is a boolean to indicate if the team member is an
    outside collaborator. The status is pretty simple.

    True = Is an outside collaborator
    False = Is a staff member
    """

    image = models.ImageField(
        verbose_name="Foto del integrante",
        upload_to="team",
        help_text="Se recomiendan imágenes de dimensiones rectangulares.",
        blank=False
    )

    name = models.CharField(
        verbose_name="Nombre del Integrante del equipo",
        max_length=100,
        help_text="Ingrese el nombre del integrante del equipo",
        default="",
        blank=False
    )

    position = models.CharField(
        verbose_name="Posición o contribución",
        max_length=100,
        help_text="Ingrese en que ha contribuido o que posición dentro\
        de UpVent tiene el integrante.",
        default="",
        blank=False
    )

    is_collab = models.BooleanField(
        verbose_name="¿Es un colaborador externo?",
        help_text="Indicar si el miembro siendo registrado es un colaborador\
        externo, de no serlo se tomará como miembro de UpVent",
        default=False,
        null=False
    )

    class Meta:
        verbose_name = "Miembro del equipo"
        verbose_name_plural = "Miembros del equipo"

    def __str__(self):
        return self.name


# (privacy-policy) Privacy Policy Project Model
class PrivacyPolicy(models.Model):

    """
    Stores a single and UNIQUE privacy policy to make this site compliant with
    inside / outside country privacy laws.

    This model has an overriden save() method to prevent more than one privacy
    policy instance to be created.
    """

    title = models.CharField(
        verbose_name="Título",
        max_length=100,
        help_text="Ingrese el título para su política de privacidad",
        default="Política de Privacidad",
        blank=False
    )

    created_on = models.DateField(
        verbose_name="Fecha de Creación",
        auto_now_add=True
    )

    updated_on = models.DateField(
        verbose_name="Fecha de Actualización",
        auto_now_add=True
    )

    changelog = models.TextField(
        verbose_name="Registro de Cambios",
        help_text="Ingrese la razón de cambiar la política de privacidad.",
        blank=False
    )

    text = RichTextUploadingField(
        verbose_name="Política de privacidad",
        help_text="Escriba aquí su política de privacidad"
    )

    class Meta:
        verbose_name = "Política de Privacidad"
        verbose_name_plural = "Política de Privacidad"

    def __str__(self):
        return self.title

    # Override 'save' method to allow only ONE instance for privacy policy
    def save(self, *args, **kwargs):
        if not self.pk and PrivacyPolicy.objects.exists():
            raise ValidationError('You cannot have multiple privacy policies')
        return super(PrivacyPolicy, self).save(*args, **kwargs)

# Terms Of Service Model
class TOS(models.Model):

    """
    Stores a single and UNIQUE terms of service + refund policy to make this
    site compliant with inside / outside country trade laws.

    This model has an overriden save() method to prevent more than one privacy
    policy instance to be created.
    """

    title = models.CharField(
        verbose_name="Título",
        max_length=100,

UpVent/core/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.http import require_GET

from blog.models import Post

from .models import (Testimonial,
                     Project,
                     FSProject,
                     License,
                     HOF,
                     TeamMember,
                     PrivacyPolicy,
                     TOS)

def index(request):
    """
    Display the main page for this site.

    **Context**

    ``testimonials``
        All instances of the :model:`core.Testimonial` saved in the database.

    **Template:**

    :template:`core/index.html`

   """

    testimonials = Testimonial.objects.all()

    context = {
        'testimonials': testimonials
    }

    return render(request, 'core/index.html', context)

def about(request):

    """
    Display the "about" page for this site.

    **Context**

    ``projects``
        All instances of the :model:`core.Project` saved in the database

    **Template**
        :template:`core/about.html`

    """

    projects = Project.objects.all()

    context = {
        'projects': projects
    }

    return render(request, 'core/about.html', context)

def services(request):

    """
    Display the "services" page for this site.

    **Context**

    ``services``
        All instances of the :model:`core.FSProject` saved in the database

    **Template**
        :template:`core/services.html`

    """

    services = FSProject.objects.all()

    context = {
        'services': services
    }

    return render(request, 'core/services.html', context)

def licenses(request):

    """
    Display the "licenses" page for this site.

    **Context**

    ``licenses``
        Return all instances of the :model:`core.License`
        saved in the database to display in the first section of the page.

    ``HOF``
        Return all instances of recognized projects shown in the
        hall of fame at the last section of the page.

    **Template**
        :template:`core/licenses.html`
    """

    licenses = License.objects.all()
    hall_of_fame = HOF.objects.all()

    context = {
        'licenses': licenses,
        'hall_of_fame': hall_of_fame,
    }

    return render(request, 'core/licenses.html', context)

def team(request):
    """
    Display the "team" page for this site.

    **Context**

    ``members``
        Return all the members with the field is_collab marked as "False".

    ``collabs``
        Return all the members with the field is_collab marked as "True".

    **Template**
        :template:`core/team.html`
    """

    members = TeamMember.objects.filter(is_collab=False)
    collabs = TeamMember.objects.filter(is_collab=True)

    context = {
        'members': members,
        'collabs': collabs,
    }

    return render(request, 'core/team.html', context)

def privacy_policy(request):

    """
    Display the "privacy-policy" page for this site.

    **Context**

    ``policies``
        Return the only instance of the :model:`core.PrivacyPolicy`
        saved in the database. This model allows ONLY ONE privacy policy.

    **Template**
        :template:`core/privacy-policy.html`

    """

    policies = PrivacyPolicy.objects.all().first()

    context = {
        'policies': policies
    }

    return render(request, 'core/privacy-policy.html', context)


def terms_service(request):

    """
    Display the "terms-of-service" page for this site.

    **Context**

    ``policies``
        Return the only instance of the :model:`marketcloud.TOS`
        saved in the database. This model allows ONLY ONE entry policy.

    **Template**
        :template:`marketcloud/tos.html`

    """

    policies = TOS.objects.all().first()

    context = {
        'policies': policies
    }

    return render(request, 'core/tos.html', context)

@require_GET
def robots_txt(request):
    """
        This renders a robots.txt file

        Modify this in production, these URL's are used as an example for
        forkers. Do this especially if you changed your admin site url.
    """
    lines = [
        "Sitemap: https://upvent.codes/sitemap.xml",
        "User-Agent: *",
        "Crawl-delay: 120",
        "Disallow: /admin/",
        "Disallow: /administration/",
        "Disallow: /administrator/",
        "Disallow: /administrador/",
        "Disallow: /administracion/",
        "Disallow: /wp-admin/",
        "Disallow: /category/",
        "Disallow: /tag/"
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

def page_not_found(request, exception):
    """
        This is a customized 404 error page when the server doesn't find
        any requested page.
    """
    return render(request, 'core/404.html', status=404)

UpVent/core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        {% block css %}{% endblock %}

        {% block metatags %}
            <!-- Primary Meta Tags -->
            <title>UpVent - Soluciones en la nube para tu negocio. Low cost, siempre listas.</title>
            <meta name="title" content="UpVent - Soluciones en la nube para tu negocio. Low cost, siempre listas.">
            <meta name="description" content="UpVent es un proveedor experto de soluciones de código libre y empresarial para los pequeños y medianos negocios Mexicanos.">

            <!-- Open Graph / Facebook -->
            <meta property="og:type" content="website">
            <meta property="og:url" content="https://upvent.codes/">
            <meta property="og:title" content="UpVent - Soluciones en la nube para tu negocio. Low cost, siempre listas">
            <meta property="og:description" content="UpVent es un proveedor experto de soluciones de código libre y empresarial para los pequeños y medianos negocios Mexicanos.">
            <meta property="og:image" content="https://upvent.codes/static/core/img/upvent-logo.png">

            <!-- Twitter -->
            <meta name="twitter:card" content="summary_large_image">
            <meta name="twitter:site" content="@UpVentMX">
            <meta name="twitter:creator" content="@UpVentMX">
            <meta name="twitter:title" content="UpVent - Soluciones en la nube para tu negocio. Low cost, siempre listas">
            <meta name="twitter:description" content="UpVent es un proveedor experto de soluciones de código libre y empresarial para los pequeños y medianos negocios Mexicanos.">
            <meta name="twitter:image" content="https://upvent.codes/static/core/img/upvent-logo.png">
        {% endblock %}

        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{% static 'core/img/favicon.ico' %}"/>
        <!-- Apple icons -->
        <link rel="apple-touch-icon" href="{% static 'core/img/apple-touch-icon.png' %}" />
        <link rel="apple-touch-icon" sizes="57x57" href="{% static 'core/img/apple-touch-icon-57x57.png' %}" />
        <link rel="apple-touch-icon" sizes="72x72" href="{% static 'core/img/apple-touch-icon-72x72.png' %}" />
        <link rel="apple-touch-icon" sizes="76x76" href="{% static 'core/img/apple-touch-icon-76x76.png' %}" />
        <link rel="apple-touch-icon" sizes="114x114" href="{% static 'core/img/apple-touch-icon-114x114.png' %}" />
        <link rel="apple-touch-icon" sizes="120x120" href="{% static 'core/img/apple-touch-icon-120x120.png' %}" />
        <link rel="apple-touch-icon" sizes="144x144" href="{% static 'core/img/apple-touch-icon-144x144.png' %}" />
        <link rel="apple-touch-icon" sizes="152x152" href="{% static 'core/img/apple-touch-icon-152x152.png' %}" />
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'core/img/apple-touch-icon-180x180.png' %}" />
        <!-- Material Bootstrap stylesheet -->
        <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}" type="text/css" media="screen"/>
        <!-- Custom stylesheet for this page -->
        <link rel="stylesheet" href="{% static 'core/css/base.css' %}" type="text/css" media="screen"/>
        <!-- VisualFX CSS for animations -->
        <link rel="stylesheet" href="{% static 'core/css/visualfx.css' %}" type="text/css" media="screen"/>
        <!-- Bootstrap icons-->
        <link rel="stylesheet" href="{% static 'core/css/bootstrap-icons.css' %}" type="text/css" media="screen"/>
        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;700;900&display=swap" rel="stylesheet">
        <!-- Mobile Web App attributes -->
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="theme-color" content="#007BFC" />
        <meta name="application-name" content="UpVent Technologies">
        <meta name="apple-mobile-web-app-title" content="UpVent Technologies">
        <meta name="apple-mobile-web-app-status-bar-style" content="blue">
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">
            You are using an <strong>outdated</strong> browser. Please
            <a href="http://browsehappy.com/">upgrade your browser</a> to improve
            your experience.
            </p>
        <![endif]-->
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-0 shadow">
            <a href="{% url 'index' %}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none navbar-brand">
                <img class="mx-auto"  width="148" height="48" src="{% static 'core/img/logo-grey.png' %}" alt="UpVent Logo">
            </a>
            <ul class="nav nav-pills col-12 mx-auto col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a {% if request.path == '/' %} class="nav-link active px-2 fw-bold" {% else %} class="nav-link px-2 link-dark" {% endif %} href="{% url 'index' %}">Inicio <i class="bi bi-house"></i></a></li>
                <li><a {% if request.path|slice:':6' == '/blog/' %} class="nav-link active px-2 fw-bold" {% else %} class="nav-link px-2 link-dark" {% endif %} href="{% url 'blog:home' %}">Blog <i class="bi bi-pen"></i></a></li>
                <li><a {% if request.path == '/about/' %} class="nav-link active px-2 fw-bold" {% else %} class="nav-link px-2 link-dark" {% endif %} href="{% url 'about' %}">Nosotros <i class="bi bi-people"></i></a></li>
                <li><a {% if request.path == '/services/' %} class="nav-link active px-2 fw-bold" {% else %} class="nav-link px-2 link-dark" {% endif %} href="{% url 'services' %}">Servicios <i class="bi bi-laptop"></i></a></li>
                <li><a {% if request.path == '/contact/' %} class="nav-link active px-2 fw-bold" {% else %} class="nav-link px-2 link-dark" {% endif %} href="{% url 'contact:home' %}">Contacto <i class="bi bi-phone"></i></a></li>
                <li><a {% if request.path == '/marketcloud/' %} class="nav-link active px-2 fw-bold" {% else %} class="nav-link px-2 link-dark" {% endif %} href="{% url 'marketcloud:home' %}">MarketCloud <i class="bi bi-bag"></i></a></li>
            </ul>
            <div class="text-end me-auto ms-auto mx-auto">
                <button type="button" class="btn btn-light border-0" title="Modo daltonismo" onclick="alert('Los colores para usuarios dalónicos aún no están listos')">👁</button>
                <noscript class="small text-muted text-wrap text-break">El modo oscuro / colores para daltonismo solo están disponibles habilitando JavaScript</noscript>
            </div>
        </header>
        {% block body %}
        {% endblock %}
        {% include 'core/footer.html' %}
        <!-- Bootstrap 5 script -->
        <script async defer type="text/javascript" src="{% static 'core/js/bootstrap.bundle.min.js' %}"></script>
        <!-- schema.org basic script -->
        <script type="application/ld+json">{"@context":"http://schema.org","@type":"Organization","name":"UpVent Technologies","url":"https://upvent.codes","address":"Guanajuato, Guanajuato","sameAs":["https://facebook.com/UpVentMX","https://twitter.com/UpVentMX","https://www.linkedin.com/company/upvent-technologies/","https://www.instagram.com/UpVentMX/"]}</script>
        <!-- custom scripts -->
        {% block js %}
        {% endblock %}
        <script type="text/javascript" src="{% static 'core/js/darkmode.js' %}"></script>
        <script type="text/javascript" src="{% static 'core/js/darkmode-config.js' %}"></script>
    </body>
</html>

UpVent/core/templates/core/footer.html
{% load static %}
<footer class="text-center text-white bg-upvent">
    <div class="container p-4">
        <section class="mb-4">
            <a class="btn btn-primary btn-floating m-1 btn-twitter" aria-label="Twitter" href="https://twitter.com/UpVentMX" rel="external" role="button"><i class="fab bi-twitter"></i></a>
            <a class="btn btn-primary btn-floating m-1 btn-instagram" aria-label="Instagram" href="https://instagram.com/UpVentMX" rel="external" role="button"><i class="fab bi-instagram"></i></a>
            <a class="btn btn-primary btn-floating m-1 btn-facebook" aria-label="Facebook" href="https://facebook.com/UpVentMX" rel="external" role="button"><i class="fab bi-facebook"></i></a>
            <a class="btn btn-primary btn-floating m-1 bg-primary" aria-label="Linkedin" href="https://www.linkedin.com/company/upvent-technologies/" rel="external" role="button"><i class="fab bi-linkedin"></i></a>
            <a class="btn btn-primary btn-floating m-1 btn-github" aria-label="GitHub" href="https://github.com/UpVent" rel="external" role="button"><i class="fab bi-github"></i></a>
            <a class="btn btn-primary btn-floating m-1 btn-secondary" aria-label="As-Card" href="https://me.as-card.com/accounts/profile/UpVentMX/" rel="external" role="button"><i class="fab bi-person-badge"></i></a>
        </section>

        <section class="mt-5">
            <div class="row">
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <div class="container">
                        <img class="img-fluid mb-1" width="116" height="47" src="{% static 'core/img/logo-white.png' %}" alt="UpVent Logo" loading="lazy"/>
                    </div>
                    <p class="text-white">Todos los derechos reservados © - UpVent {% now "Y" %}. Todos los logos son marcas registradas de sus respectivos dueños.</p>
                </div>

                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <p class="h4 text-uppercase">Enlaces Rápidos</p>
                    <ul class="list-unstyled mb-0">
                        <li class="m-2">
                            <a href="{% url 'index' %}" class="fs-5 text-white text-decoration-none">Inicio <i class="bi bi-house"></i></a>
                        </li>
                        <li class="m-2">
                            <a href="{% url 'blog:home' %}" class="fs-5 text-white text-decoration-none">Blog <i class="bi bi-pen"></i></a>
                        </li>
                        <li class="m-2">
                            <a href="{% url 'about' %}" class="fs-5 text-white text-decoration-none">Nosotros <i class="bi bi-people"></i></a>
                        </li>
                        <li class="m-2">
                            <a href="{% url 'services' %}" class="fs-5 text-white text-decoration-none">Servicios <i class="bi bi-laptop"></i></a>
                        </li>
                        <li class="m-2">
                            <a href="{% url 'contact:home' %}" class="fs-5 text-white text-decoration-none">Contacto <i class="bi bi-phone"></i></a>
                        </li>
                        <li class="m-2">
                            <a href="{% url 'marketcloud:home' %}" class="fs-5 text-white text-decoration-none">MarketCloud <i class="bi bi-bag"></i></a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <p class="h4 text-uppercase">Enlaces Importantes</p>
                    <ul class="list-unstyled mb-0">
                        <li class="m-2">
                            <a href="https://github.com/UpVent" class="fs-5 text-white text-decoration-none">Repositorio de Código Libre en GitHub <i class="bi bi-github"></i></a>
                        </li>
                        <li class="m-2">
                            <a href="{% url 'team' %}" class="fs-5 text-white text-decoration-none">Equipo <i class="bi bi-diagram-3"></i></a>
                        </li>
                        <li class="m-2">
                            <a href="{% url 'licenses' %}" class="fs-5 text-white text-decoration-none">Licencias <i class="bi bi-journal-text"></i></a>
                        </li>
                        <li class="m-2">
                            <a rel="nofollow" href="https://tickets.upvent.codes" class="fs-5 text-white text-decoration-none">Sistema de Soporte <i class="bi bi-info-circle"></i></a>
                        </li>
                        <li class="m-2">
                            <a href="#!" class="text-white text-decoration-none">...Espera más contenido pronto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </section>
    </div>

    <section class="container mt-5 mb-5 text-center-p-4">
        <p class="text-white fs-6">
            El <a href="https://github.com/UpVent/upvent.codes" class="text-white">código fuente</a> de esta página se encuentra bajo la <a class="text-white" href="https://www.gnu.org/licenses/old-licenses/gpl-2.0.html">Licencia Pública General de GNU versión 2</a>. Excepto donde se indique lo <a class="text-white" href="https://creativecommons.org/policies#license">contrario</a>, el trabajo escrito, blogs, opiniones y parte del contenido visual se encuentra bajo la <a class="text-white" href="https://creativecommons.org/licenses/by-nd/3.0/deed.es">Licencia Creative Commons Atribución-SinDerivadas 3.0 No portada (CC BY-ND 3.0)</a>
        </p>
    </section>

    <section class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © {% now "Y" %} Copyright:
        <a class="text-white" href="https://upvent.codes/">UpVent Technologies</a> -
        <a class="text-white" href="{% url 'privacy-policy' %}"> Política de privacidad</a> -
        <a class="text-white" href="{% url 'terms-of-service' %}">Términos y Condiciones del servicio</a> -
        <a class="text-white" href="https://github.com/UpVent/upvent.codes/issues/new">Reportar un problema con este sitio</a>
    </section>
</footer>