UpVent/UpVent/urls.py
# Import settings if not imported
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

# Import robots.txt
from core.views import robots_txt

# Import sitemaps
from core.sitemaps import StaticViewSitemap, BlogSitemap

handler404 = 'core.views.page_not_found'

sitemaps = {
    'static': StaticViewSitemap,
    'posts': BlogSitemap,
}

urlpatterns = [
    # Special URL's (Mostly admin or managed things)
    path('wp-admin/doc/', include('django.contrib.admindocs.urls')),
    path('captcha/', include('captcha.urls')),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('wp-admin/', admin.site.urls),
    path('robots.txt', robots_txt),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    # Main Site URLs
    path('', include('core.urls'), name='index'),
    path('blog/', include('blog.urls', namespace="blog"), name='blog'),
    path('contact/', include('contact.urls', namespace="contact"),
         name='contact'),
    path('marketcloud/', include('marketcloud.urls', namespace="marketcloud"),
         name='marketcloud'),
]

admin.site.site_header = "UpVent Admin"
admin.site.index_title = "Admin"
admin.site.site_title = "UpVent"

# Special URL's for development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UpVent/blog/urls.py
from django.urls import path
from .views import Blog, BlogEntry, BlogSearch

app_name = 'blog'

urlpatterns = [
    path('', Blog, name='home'),
    path('entry/<slug>/', BlogEntry, name='post'),
    path('search/', BlogSearch, name='blog-search'),
]

UpVent/marketcloud/urls.py
from . import views
from django.urls import path
from .views import MarketCloud, Item

app_name = 'marketcloud'

urlpatterns = [
    path('', MarketCloud, name='home'),
    path('<slug:slug>/', Item, name='item')
]

UpVent/marketcloud/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

class Product(models.Model):

    STATUS = (
        (0, "Agotado"),
        (1, "Disponible")
    )

    icon = models.ImageField(
        verbose_name="Ícono del producto",
        upload_to="store"
    )

    name = models.CharField(
        verbose_name="Nombre del Producto",
        max_length=50,
        unique=True,
        help_text="Ingrese el nombre del producto",
        default="",
        blank=False
    )

    slug = models.SlugField(
        verbose_name="Slug",
        max_length=200,
        unique=True,
        help_text="Campo autogenerado. Modifique de acuerdo a sus necesidades",
        blank=False
    )

    # This is expressed in cents
    price = models.DecimalField(
        verbose_name="Precio del Producto",
        decimal_places=2,
        max_digits=8,
        help_text="Ingrese el precio del producto. Es recomendable usar solo\
        dos decimales en caso de necesitar el uso de los mismos.",
        default=0
    )

    category = models.CharField(
        verbose_name="Categoría del producto",
        max_length=50,
        help_text="Ingrese la categoría a la que pertenece el producto.\
        e.g: Herramientas de Desarrollador, Frameworks, Blogs y Foros.",
        default="",
        blank=False
    )

    apptype = models.CharField(
        verbose_name="Tipo de aplicación",
        max_length=50,
        help_text="Ingrese el tipo de aplicación que es el producto.\
        e.g: Suscripción, App de 1 click, etc.",
        default="",
        blank=False
    )

    short_description = models.TextField(
        verbose_name="Descripción corta del producto",
        help_text="Ingrese una descripción corta del producto.",
        default="",
        blank=False
    )

    description = RichTextUploadingField(
        verbose_name="Descripción detallada del producto",
        help_text="Ingrese una descripción detallada del producto."
    )

    stripe_link = models.URLField(
        verbose_name="Enlace para pagos con cripto en Stripe",
        help_text="Ingrese el enlace para pagos con stipe",
        blank=True
    )

    created_on = models.DateTimeField(
        verbose_name="Creado el: ",
        auto_now_add=True
    )

    updated_on = models.DateTimeField(
        verbose_name="Actualizado el: ",
        auto_now_add=True
    )

    # Product inventory status
    status = models.IntegerField(
        choices=STATUS,
        default=0,
        help_text="Estatus actual del producto"
    )

    class Meta:
        ordering = ['created_on']
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def __str__(self):
        return self.name

UpVent/marketcloud/views.py
from django.shortcuts import render

from .models import Product

def MarketCloud(request):

    products = Product.objects.filter(status=1).order_by("created_on")


    context = {
        'products': products
    }

    return render(request, 'marketcloud/shop.html', context)

def Item(request, slug):

    product = Product.objects.get(slug=slug)

    context = {
        'product': product
    }

    return render(request, 'marketcloud/product.html', context)

UpVent/marketcloud/templates/marketcloud/product.html
{% extends 'core/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'marketcloud/css/shop.css' %}" type="text/css" media="screen" />
{% endblock %}

{% block metatags %}
    <!-- Primary Meta Tags -->
    <title>{{product.name}} | UpVent - MarketCloud</title>
    <meta name="title" content=" {{product.name}} | UpVent - MarketCloud">
    <meta name="description" content="Conoce los últimos productos, soluciones y servicios que UpVent puede ofrecerle a tu negocio.">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://upvent.codes/marketcloud/{{product.slug}}">
    <meta property="og:title" content="{{product.name}} | UpVent - MarketCloud">
    <meta property="og:description" content="Conoce los últimos productos, soluciones y servicios que UpVent puede ofrecerle a tu negocio.">
    <meta property="og:image" content="https://upvent.codes/static/marketcloud/img/core-marketcloud.png">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@UpVentMX">
    <meta name="twitter:creator" content="@UpVentMX">
    <meta name="twitter:title" content="{{product.name}} | UpVent - MarketCloud">
    <meta name="twitter:description" content="Conoce los últimos productos, soluciones y servicios que UpVent puede ofrecerle a tu negocio.">
    <meta name="twitter:image" content="https://upvent.codes/static/marketcloud/img/core-marketcloud.png">
{% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 mb-2">
                <section class="mb-2">
                    <img src="{{product.icon.url}}" height="66" width="66" class="img-thumbnail m-3" alt="" />
                    <h1 class="h1 text-primary">{{product.name}}</h1>

                    <div class="row align-items-center mb-4">
                        <div class="col-lg-6 text-center text-lg-start mb-3 m-lg-0">
                            <p class="badge bg-primary rounded-pill">{{product.category}}</p>
                        </div>

                        <div class="col-lg-6 text-center text-lg-end">
                            <span class="badge bg-secondary rounded-pill px-3 me-1">
                                {{product.apptype}}
                            </span>
                        </div>
                    </div>
                </section>

                <section>
                    <h2 class="text-secondary fw-bold">Descripción</h2>
                    <p class="text-muted">
                        {{product.short_description}}
                    </p>
                </section>

                <hr />

                <section class="border-bottom">
                    <p>
                        {{product.description|safe}}
                    </p>
                </section>
            </div>

            <div class="col-md-4 mb-4">
                <section class="sticky-top" style="top: 80px;">
                    <section class="text-center border-bottom pb-4 mb-4">
                        <p class="h3">${{product.price}} MXN</p>
                        <div class="d-grid gap-2">
                            {% if product.stripe_link is not none %}
                            <a class="btn btn-lg btn-primary" href="{{product.stripe_link}}" target="_blank">Comprar <i class="bi bi-credit-card ms-2"></i></a>
                            {% else %}
                                <a class="btn btn-lg btn-danger" onclick="alert('no mames que agotado dicen');">No disponible <i class="bi bi-bag-x ms-2"></i></a>
                            {% endif %}
                        </div>
                        <div class="d-flex mt-2 mb-2">
                            <img class="w-50 mx-auto d-block" src="{% static 'marketcloud/img/stripe.svg' %}" alt="medalla de stripe"/>
                        </div>
                    </section>

                    <section>
                        <h5 class="mb-4">Instrucciones de compra</h5>
                        <p class="text-muted">
                            Una vez hecho su pago, recibirá dos correos electrónicos en su bandeja de entrada. De no recibirlos, por favor revise su carpeta de <i>spam</i>.
                        </p>
                        <p class="text-muted">
                            Uno de estos correos será de confirmación incluyendo un recibo de compra.
                            El segundo correo será su usuario + acceso al sistema de soporte gratuito para clientes de UpVent
                        </p>
                        <h5 class="mt-4 mb-4">Detalles de soporte</h5>
                        <p>Sistema de soporte gratuito para clientes: <a href="https://tickets.upvent.codes">https://tickets.upvent.codes</a></p>
                        <h5 class="mt-4 mb-4">Enlaces de ayuda</h5>
                        <ul>
                            <li><a href="{% url 'privacy-policy' %}">Política de privacidad</a></li>
                            <li><a href="{% url 'terms-of-service' %}">Términos y condiciones de compra + Política de Reembolsos</a></li>
                        </ul>
                        <a href="https://www.digitalocean.com/?refcode=6f611e36e863&utm_campaign=Referral_Invite&utm_medium=Referral_Program&utm_source=badge"><img src="https://web-platforms.sfo2.digitaloceanspaces.com/WWW/Badge%203.svg" alt="DigitalOcean Referral Badge" /></a>
                    </section>
                </section>
            </div>
        </div>
    </div>
{% endblock %}

UpVent/marketcloud/templates/marketcloud/shop.html
{% extends 'core/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'marketcloud/css/shop.css' %}" type="text/css" media="screen" />
{% endblock %}
{% block metatags %}
    <!-- Primary Meta Tags -->
    <title>UpVent - MarketCloud. La tienda oficial de UpVent para desarrolladores y empresarios.</title>
    <meta name="title" content="UpVent - MarketCloud. La tienda oficial de UpVent para desarrolladores y empresarios.">
    <meta name="description" content="Conoce los últimos productos, soluciones y servicios que UpVent puede ofrecerle a tu negocio.">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://upvent.codes/marketcloud/">
    <meta property="og:title" content="UpVent - MarketCloud. La tienda oficial de UpVent para desarrolladores y empresarios.">
    <meta property="og:description" content="Conoce los últimos productos, soluciones y servicios que UpVent puede ofrecerle a tu negocio.">
    <meta property="og:image" content="https://upvent.codes/static/core/img/core-marketplace.png">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@UpVentMX">
    <meta name="twitter:creator" content="@UpVentMX">
    <meta name="twitter:title" content="UpVent - MarketCloud. La tienda oficial de UpVent para desarrolladores y empresarios.">
    <meta name="twitter:description" content="Conoce los últimos productos, soluciones y servicios que UpVent puede ofrecerle a tu negocio.">
    <meta name="twitter:image" content="https://upvent.codes/static/core/img/core-marketplace.png">
{% endblock %}
{% block body %}
    <section class="p-5 text-center bg-image jumbotron">
        <div class="d-flex justify-content-center align-items-center m-5 h-100">
            <div class="text-white">
                <h1 class="text-center display-3 mb-3">
                    MarketCloud <i class="bi bi-bag"></i>
                </h1>

                <div class="container">
                    <p class="lead text-center text-wrap mb-3">
                        Encuentre una solución que se adapte a sus necesidades. Hay disponibles una gran cantidad de aplicaciones preconfiguradas de 1 clic, incluidas WordPress, E-Commerce, Servidores Automanejados, Panel de Hosting y más.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- Products  -->
    <section class="container mt-5 mb-5">
        <p class="h4">Selecciones del editor</p>
        <hr />
    </section>

    <section class="container mt-5 mb-5">
        <div class="row row-cols-5 row-cols-xs-1 row-cols-sm-1 row-cols-md-5 gx-2 gy-3">
            {% for product in products %}
            <div class="col-auto">
                <article class="card border-0 shadow-sm">
                    <img class="rounded-3 img-thumbnail m-1" src="{{product.icon.url}}" height="80" width="80" class="m-2" alt="{{product.name}}">
                    <div class="card-body mt-3">
                        <p class="h5 text-primary text-wrap text-break">{{product.name}}</p>
                        <p class="m-0 text-muted">{{product.category}}</p>
                        <p class="m-0 fw-bold">{{product.apptype}}</p>
                        <p class="small text-muted text-wrap text-break"><small class="card-text">{{product.short_description|truncatewords:10}}</small></p>
                        <a href="{% url 'marketcloud:item' product.slug %}" class="btn btn-primary stretched-link fw-light">Comprar <i class="bi bi-cart"></i></a>
                    </div>
                </article>
            </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}